services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    container_name: nuxt_frontend
    environment:
      API_URL: "http://158.160.180.181:1337/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strapi_backend
    env_file: ./backend/.env
    ports:
      - "1337:1337"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
      - ./backend/.tmp:/app/.tmp
