name: Deploy Docker Containers

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3 

      - name: Установка Docker и Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Запуск контейнеров
        run: |
          docker-compose down 
          docker-compose up -d --build  
