version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vessels-manual-backend:latest
    container_name: strapi_backend
    env_file:
      - ./backend/.env
    ports:
      - "1337:1337"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
      - ./backend/.tmp:/app/.tmp
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vessels-manual-frontend:latest
    container_name: nuxt_frontend
    environment:
      - API_URL=http://backend:1337/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
