services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    container_name: nuxt_frontend
    environment:
      API_URL: "http://158.160.173.105/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend

version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strapi_backend
    env_file: ./backend/.env
    ports:
      - "1337:1337"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
      - ./backend/.tmp:/app/.tmp
    container_name: myapp_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myapp_frontend
    ports:
      - "3000:80"
