version: '3.8'

services:
  backend:
    image: your_dockerhub_user/backend:latest
    container_name: myapp_backend
    ports:
      - "8000:8000"  
    environment:
      - ENV=production

  frontend:
    image: your_dockerhub_user/frontend:latest
    container_name: myapp_frontend
    ports:
      - "3000:80"     
